# Generated by Django 4.1.6 on 2023-02-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tiltle',
            new_name='name',
        ),
    ]
